print('Welcome!')
print('This is a cow and bull game!')
print('cow(s) represent number(s) of digit(s) guessed correctly in the correct place')
print('bull(s) represent number(s) of digit(s) guessed correctly in the wrong place')
print('')
import random
c = str(random.randint(0,9))
d = str(random.randint(0,9))
f = str(random.randint(0,9))
g = str(random.randint(0,9))
secretnumber = (c+d+f+g)
guessnumber = 0
while True:
    try:
        while guessnumber >= 0:
             print('Take a four digit guess!')
             print(secretnumber) ##Cracks out the number
             guess = input()
             dummy = int(guess)
             if len(guess) == 4:
                 guessnumber += 1
                 cow = 0
                 for i in range(4):
                      if guess[i] == secretnumber[i]:
                          cow += 1
                 bull = 0
                 for k in range(4):
                     for j in range(4):
                            if (guess[k] == secretnumber[j]) and (k != j):
                                    bull += 1
                 if guess == secretnumber:
                    print('The number generated by the computer is ' + str(secretnumber))
                    print('')
                    print('you guess right in ' + str(guessnumber) + ' guess')
                    import sys
                    sys.exit()
                 else:
                    print(str(cow) + ' cow(s)' , str(bull) + ' bull(s)')
                    print('')

             else:
                 if len(guess) < 4:
                     print('(There is only ' + str(len(guess)) + ' digit(s))')
                     print('')
                 else:
                     print('(There is ' + str(len(guess)) + ' digits)')
                     print('')
    except ValueError:
        print("You didn't Enter pure numeric digits")
        print('')

                            
                
             
             


         



